### ISSUE TITLE
go-callvis is crashing while browsing through ....

### ISSUE THREAD

**Issue by rahamannaik** [ofabry/go-callvis#101]
Hi Team,

     I just installed the go-callvis and tried to explore it. While doing so, it's getting crashed.
     Here is the backtrace.

2021/09/15 12:44:23 http serving at http://localhost:7878
Error: no DISPLAY environment variable specified
2021/09/15 12:46:50 converting dot to svg..
2021/09/15 12:46:50 serving file: /tmp/go-callvis_export.svg
2021/09/15 12:47:09 converting dot to svg..
2021/09/15 12:47:10 serving file: /tmp/go-callvis_export.svg
2021/09/15 12:49:02 converting dot to svg..
2021/09/15 12:49:02 serving file: /tmp/go-callvis_export.svg
2021/09/15 12:50:00 converting dot to svg..
2021/09/15 12:50:00 serving file: /tmp/go-callvis_export.svg
2021/09/15 12:50:08 converting dot to svg..
2021/09/15 12:50:08 serving file: /tmp/go-callvis_export.svg
2021/09/15 12:50:23 converting dot to svg..
2021/09/15 12:50:34 converting dot to svg..
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7eff7771037e]

runtime stack:
runtime.throw(0xbce70e, 0x2a)
	/usr/lib/go/src/runtime/panic.go:774 +0x72
runtime.sigpanic()
	/usr/lib/go/src/runtime/signal_unix.go:378 +0x47c

goroutine 9872 [syscall]:
runtime.cgocall(0x96dcf0, 0xc01cc3d860, 0x3)
	/usr/lib/go/src/runtime/cgocall.go:128 +0x5b fp=0xc01cc3d830 sp=0xc01cc3d7f8 pc=0x41c9bb
github.com/goccy/go-graphviz/internal/ccall._Cfunc_gvLayout(0x7eff48000ba0, 0x7eff4802e630, 0x7eff4800d750, 0x0)
	_cgo_gotypes.go:2372 +0x4d fp=0xc01cc3d860 sp=0xc01cc3d830 pc=0x8d271d
github.com/goccy/go-graphviz/internal/ccall.GvLayout.func1(0xc069273d60, 0xc0b9fd21d0, 0xbb7555, 0x3, 0x0)
	/home/fnaik/go/src/github.com/goccy/go-graphviz/internal/ccall/gvc.go:736 +0xe7 fp=0xc01cc3d8b0 sp=0xc01cc3d860 pc=0x8e25b7
github.com/goccy/go-graphviz/internal/ccall.GvLayout(0xc069273d60, 0xc0b9fd21d0, 0xbb7555, 0x3, 0x1a, 0xc045f05360)
	/home/fnaik/go/src/github.com/goccy/go-graphviz/internal/ccall/gvc.go:736 +0x49 fp=0xc01cc3d8e8 sp=0xc01cc3d8b0 pc=0x8dde99
github.com/goccy/go-graphviz/gvc.(*Context).Layout(...)
	/home/fnaik/go/src/github.com/goccy/go-graphviz/gvc/gvc.go:29
github.com/goccy/go-graphviz.(*Graphviz).RenderFilename(0xc058d7f080, 0xc0b9fd21d8, 0xbb75d0, 0x3, 0xc045f05360, 0x1a, 0x0, 0x0)
	/home/fnaik/go/src/github.com/goccy/go-graphviz/graphviz.go:115 +0x73 fp=0xc01cc3d980 sp=0xc01cc3d8e8 pc=0x95a3b3
main.dotToImage(0x0, 0x0, 0xbb75d0, 0x3, 0xc030016000, 0xf88d7, 0xf88d7, 0x0, 0x0, 0x0, ...)
	/home/fnaik/go/src/github.com/ofabry/go-callvis/dot.go:77 +0x29c fp=0xc01cc3dab0 sp=0xc01cc3d980 pc=0x96293c
main.handler(0xc97300, 0xc0974ec7e0, 0xc086dc0000)
	/home/fnaik/go/src/github.com/ofabry/go-callvis/handler.go:53 +0x495 fp=0xc01cc3db90 sp=0xc01cc3dab0 pc=0x963805
net/http.HandlerFunc.ServeHTTP(0xbddf88, 0xc97300, 0xc0974ec7e0, 0xc086dc0000)
	/usr/lib/go/src/net/http/server.go:2007 +0x44 fp=0xc01cc3dbb8 sp=0xc01cc3db90 pc=0x7c3fc4
net/http.(*ServeMux).ServeHTTP(0x1126c80, 0xc97300, 0xc0974ec7e0, 0xc086dc0000)
	/usr/lib/go/src/net/http/server.go:2387 +0x1bd fp=0xc01cc3dc18 sp=0xc01cc3dbb8 pc=0x7c5e9d
net/http.serverHandler.ServeHTTP(0xc0974ec380, 0xc97300, 0xc0974ec7e0, 0xc086dc0000)
	/usr/lib/go/src/net/http/server.go:2802 +0xa4 fp=0xc01cc3dc48 sp=0xc01cc3dc18 pc=0x7c7414
net/http.(*conn).serve(0xc0798100a0, 0xc982c0, 0xc17fe38000)
	/usr/lib/go/src/net/http/server.go:1890 +0x875 fp=0xc01cc3dfc8 sp=0xc01cc3dc48 pc=0x7c2db5
runtime.goexit()
	/usr/lib/go/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc01cc3dfd0 sp=0xc01cc3dfc8 pc=0x4740f1
created by net/http.(*Server).Serve
	/usr/lib/go/src/net/http/server.go:2928 +0x384

goroutine 1 [IO wait]:
internal/poll.runtime_pollWait(0x7eff74231ad8, 0x72, 0x0)
	/usr/lib/go/src/runtime/netpoll.go:184 +0x55
internal/poll.(*pollDesc).wait(0xc099d01b98, 0x72, 0x0, 0x0, 0xbb86c5)
	/usr/lib/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	/usr/lib/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Accept(0xc099d01b80, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/go/src/internal/poll/fd_unix.go:384 +0x1f8
net.(*netFD).accept(0xc099d01b80, 0xc0edd2fc88, 0x7c83a4, 0xc0974ec420)
	/usr/lib/go/src/net/fd_unix.go:238 +0x42
net.(*TCPListener).accept(0xc03176dac0, 0x61419ea7, 0xc0edd2fc88, 0x4d37a6)
	/usr/lib/go/src/net/tcpsock_posix.go:139 +0x32
net.(*TCPListener).Accept(0xc03176dac0, 0xc0edd2fcd8, 0x18, 0xc000000180, 0x7c78d4)
	/usr/lib/go/src/net/tcpsock.go:261 +0x47
net/http.(*Server).Serve(0xc0974ec380, 0xc97040, 0xc03176dac0, 0x0, 0x0)
	/usr/lib/go/src/net/http/server.go:2896 +0x280
net/http.(*Server).ListenAndServe(0xc0974ec380, 0xc0974ec380, 0xc0edd2ff20)
	/usr/lib/go/src/net/http/server.go:2825 +0xb7
net/http.ListenAndServe(...)
	/usr/lib/go/src/net/http/server.go:3081
main.main()
	/home/fnaik/go/src/github.com/ofabry/go-callvis/main.go:157 +0x32d

goroutine 9866 [IO wait]:
internal/poll.runtime_pollWait(0x7eff74231d48, 0x72, 0xffffffffffffffff)
	/usr/lib/go/src/runtime/netpoll.go:184 +0x55
internal/poll.(*pollDesc).wait(0xc09a108098, 0x72, 0x1000, 0x1000, 0xffffffffffffffff)
	/usr/lib/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	/usr/lib/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc09a108080, 0xc05a4da000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/lib/go/src/internal/poll/fd_unix.go:169 +0x1cf
net.(*netFD).Read(0xc09a108080, 0xc05a4da000, 0x1000, 0x1000, 0xc000abb7e0, 0x4dbc42, 0xc09597e060)
	/usr/lib/go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc0ba0ec000, 0xc05a4da000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/lib/go/src/net/net.go:184 +0x68
net/http.(*connReader).Read(0xc06ddd6210, 0xc05a4da000, 0x1000, 0x1000, 0xc09a0a8480, 0x0, 0x3000000000)
	/usr/lib/go/src/net/http/server.go:785 +0xf4
bufio.(*Reader).fill(0xc095dd8000)
	/usr/lib/go/src/bufio/bufio.go:100 +0x103
bufio.(*Reader).ReadSlice(0xc095dd8000, 0xc0970c280a, 0x7eff38a3f020, 0xc000abb9a8, 0x4258e6, 0xc086e00000, 0x100)
	/usr/lib/go/src/bufio/bufio.go:359 +0x3d
bufio.(*Reader).ReadLine(0xc095dd8000, 0xc000abb9b0, 0xc000192000, 0x7eff776328b8, 0x0, 0xb8a8e0, 0xc06e2507b0)
	/usr/lib/go/src/bufio/bufio.go:388 +0x34
net/textproto.(*Reader).readLineSlice(0xc06e2507b0, 0xc086e00000, 0xc09a108080, 0x0, 0x0, 0x4496ac)
	/usr/lib/go/src/net/textproto/reader.go:57 +0x6c
net/textproto.(*Reader).ReadLine(...)
	/usr/lib/go/src/net/textproto/reader.go:38
net/http.readRequest(0xc095dd8000, 0x0, 0xc086e00000, 0x0, 0x0)
	/usr/lib/go/src/net/http/request.go:1012 +0x92
net/http.(*conn).readRequest(0xc07491a140, 0xc982c0, 0xc008bd6a40, 0x0, 0x0, 0x0)
	/usr/lib/go/src/net/http/server.go:965 +0x15f
net/http.(*conn).serve(0xc07491a140, 0xc982c0, 0xc008bd6a40)
	/usr/lib/go/src/net/http/server.go:1817 +0x6d4
created by net/http.(*Server).Serve
	/usr/lib/go/src/net/http/server.go:2928 +0x384

goroutine 9878 [syscall]:
github.com/goccy/go-graphviz/internal/ccall._Cfunc_gvLayout(0x7eff5c000cd0, 0x7eff5c198270, 0x7eff5c000f50, 0x0)
	_cgo_gotypes.go:2372 +0x4d
github.com/goccy/go-graphviz/internal/ccall.GvLayout.func1(0xc0b58e23d8, 0xc0b58e23e8, 0xbb7555, 0x3, 0x0)
	/home/fnaik/go/src/github.com/goccy/go-graphviz/internal/ccall/gvc.go:736 +0xe7
github.com/goccy/go-graphviz/internal/ccall.GvLayout(0xc0b58e23d8, 0xc0b58e23e8, 0xbb7555, 0x3, 0x1a, 0xc01adcbd80)
	/home/fnaik/go/src/github.com/goccy/go-graphviz/internal/ccall/gvc.go:736 +0x49
github.com/goccy/go-graphviz/gvc.(*Context).Layout(...)
	/home/fnaik/go/src/github.com/goccy/go-graphviz/gvc/gvc.go:29
github.com/goccy/go-graphviz.(*Graphviz).RenderFilename(0xc0183cdb30, 0xc0b58e23f0, 0xbb75d0, 0x3, 0xc01adcbd80, 0x1a, 0x0, 0x0)
	/home/fnaik/go/src/github.com/goccy/go-graphviz/graphviz.go:115 +0x73
main.dotToImage(0x0, 0x0, 0xbb75d0, 0x3, 0xc020710000, 0xf88d7, 0xf88d7, 0x0, 0x0, 0x0, ...)
	/home/fnaik/go/src/github.com/ofabry/go-callvis/dot.go:77 +0x29c
main.handler(0xc97300, 0xc0974ec000, 0xc084885b00)
	/home/fnaik/go/src/github.com/ofabry/go-callvis/handler.go:53 +0x495
net/http.HandlerFunc.ServeHTTP(0xbddf88, 0xc97300, 0xc0974ec000, 0xc084885b00)
	/usr/lib/go/src/net/http/server.go:2007 +0x44
net/http.(*ServeMux).ServeHTTP(0x1126c80, 0xc97300, 0xc0974ec000, 0xc084885b00)
	/usr/lib/go/src/net/http/server.go:2387 +0x1bd
net/http.serverHandler.ServeHTTP(0xc0974ec380, 0xc97300, 0xc0974ec000, 0xc084885b00)
	/usr/lib/go/src/net/http/server.go:2802 +0xa4
net/http.(*conn).serve(0xc072de8000, 0xc982c0, 0xc17fe34400)
	/usr/lib/go/src/net/http/server.go:1890 +0x875
created by net/http.(*Server).Serve
	/usr/lib/go/src/net/http/server.go:2928 +0x384

goroutine 9894 [IO wait]:
internal/poll.runtime_pollWait(0x7eff74231ee8, 0x72, 0xffffffffffffffff)
	/usr/lib/go/src/runtime/netpoll.go:184 +0x55
internal/poll.(*pollDesc).wait(0xc0b764c098, 0x72, 0x0, 0x1, 0xffffffffffffffff)
	/usr/lib/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	/usr/lib/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc0b764c080, 0xc075674131, 0x1, 0x1, 0x0, 0x0, 0x0)
	/usr/lib/go/src/internal/poll/fd_unix.go:169 +0x1cf
net.(*netFD).Read(0xc0b764c080, 0xc075674131, 0x1, 0x1, 0xc7af75, 0xc00134f768, 0x48f1dc)
	/usr/lib/go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc082b12038, 0xc075674131, 0x1, 0x1, 0x0, 0x0, 0x0)
	/usr/lib/go/src/net/net.go:184 +0x68
net/http.(*connReader).backgroundRead(0xc075674120)
	/usr/lib/go/src/net/http/server.go:677 +0x58
created by net/http.(*connReader).startBackgroundRead
	/usr/lib/go/src/net/http/server.go:673 +0xd4

**Comment by jihenry** [comment]
i hit this problem when click pkg.
