### ISSUE TITLE
panic: in crypto/sha256.Sum224: cannot convert slice t0[:] ([]byte) to *[28]byte

### ISSUE THREAD

**Issue by tantingting1012** [ofabry/go-callvis#115]

**Comment by smjure** [comment]
I am getting the same error

**Comment by Kevinello** [comment]
me too

**Comment by Kevinello** [comment]
It looks like it's the reasons for not adapting to go 1.18, when i set it back to go 1.17.8 it worked perfectly

**Comment by smjure** [comment]
Thank for the feedback. I have tried with both, first actually with 1.17 and then 1.18 and it gives the same panic.

**Comment by dreamerlzl** [comment]
Same error here, with go 1.18.1 linux/arm64.

**Comment by dreamerlzl** [comment]
I found this, probably this error is unrelated to go-callvis.
https://github.com/golang/go/issues/51822

**Comment by medyagh** [comment]
same issue, tired it with minikube
```
$ go-callvis ./cmd/minikube
panic: in crypto/sha512.Sum384: cannot convert slice t0[:] ([]byte) to *[48]byte

goroutine 15576 [running]:
golang.org/x/tools/go/ssa.emitConv(0x14038d55680, {0x102848cb8, 0x1406f5d8780}, {0x102844788?, 0x1400f66e330})
    /Users/medya/go/pkg/mod/golang.org/x/tools@v0.0.0-20200305224536-de023d59a5d1/go/ssa/emit.go:242 +0x6b8
golang.org/x/tools/go/ssa.(*builder).expr0(0x1027b5ae0?, 0x14038d55680, {0x102845680?, 0x1400f2cd0c0}, {0x7, {0x102844788, 0x1400f66e330}, {0x0, 0x0}})
    /Users/medya/go/pkg/mod/golang.org/x/tools@v0.0.0-20200305224536-de023d59a5d1/go/ssa/builder.go:573 +0x824
golang.org/x/tools/go/ssa.(*builder).expr(0x10280e8c0?, 0x14038d55680, {0x102845680?, 0x1400f2cd0c0?})
    /Users/medya/go/pkg/mod/golang.org/x/tools@v0.0.0-20200305224536-de023d59a5d1/go/ssa/builder.go:530 +0x13c
golang.org/x/tools/go/ssa.(*builder).assign(0x14038d55680?, 0x14038d55680?, {0x102846968?, 0x1406f5d2d80}, {0x102845680?, 0x1400f2cd0c0?}, 0x0?, 0x1404de875a0)
```

**Comment by ofabry** [comment]
Possibly fixed by #121 ?

**Comment by Antonboom** [comment]
+1

**Comment by feng99** [comment]
mee  to .  how to solve ?

**Comment by bozhen-liu** [comment]
follow up, any solution?
